https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/locket.module
https://raw.githubusercontent.com/dhungx/modules-shadowrocket/main/youtube.module
[MITM]
hostname = %APPEND% new.hostname.com

[Script]
spotify-json = type=http-request,type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.github[...]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,max-size=0,script-[...]
[Script]

spotify歌词翻译 = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/color-lyrics\/v2\/track\/,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubuserconten[...]



/*



-----------申请百度翻译(有标准版和高级版 建议申请高级版)api--------------

2022年8月1日起，通用翻译API标准版免费调用量调整为5万字符/月，高级版免费调用量调整为100万字符/月

    注册百度翻译个人开发者: http://api.fanyi.baidu.com/register

    注册后如果需要认证可自行选择是否实人认证(高级版需要验证)

    开通(通用翻译)API服务: https://fanyi-api.baidu.com/choose

    成功后即可看到自己的appid和密钥(不要泄露给任何人): http://api.fanyi.baidu.com/manage/developer



*/



[MITM]

hostname = %APPEND% new.hostname.com
